; generated by Slic3r 0.8.5-dev on 2012-07-17 at 13:40:22

; layer_height = 0.4
; perimeters = 3
; solid_layers = 3
; fill_density = 0.4
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; scale = 1
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; single wall width = 0.53mm
; first layer single wall width = 0.80mm

M104 S200 ; set temperature
G28 ; home all axes
M109 S200 ; wait for temperature to be reached
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0
M82 ; use absolute distances for extrusion
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

; filament used = 0.0mm (0.0cm3)
